### ISSUE TITLE
Improve pre-commit configuration.

### ISSUE THREAD

**Issue by romulogoncalves** [FernLab/cookiecutter-py-package#1]
- [x] The default python version should not be hard-coded.
- [x] It should cover the same checks as in the previous make lint

**Comment by Jen-Wenzel** [comment]
Implemented the above mentioned changes -> https://github.com/FernLab/cookiecutter-py-package/pull/13

- [ ] Included the following linters within Ruff: Pyflakes, pycodestyle, mccabe complexity, isort, pep8-naming, pydocstyle, pyupgrade, bandit, flake8-bugbear and flake8-simplify. These linters should cover the same checks in addition to other common checks while balancing verbosity and full coverage. 
- [ ]  Enabled preview linting rules since they add relevant checks and have proven to be sufficiently stable
- [ ]  Added automatic fixing of simple formatting errors
- [ ]  Added relevant comments for help 
- [ ]  Updated pre-commit repo versions
- [ ]  Extensively tested the use of pre-commit hooks with cookiecutter  
- [ ]  Simplified pre-commit config by i.e. removing redundant linters

**Comment by romulogoncalves** [comment]
@Jen-Wenzel would it be possible to make the old `make lint` the default option and have the new pre-commit as optional? We think the new pre-commit is nice for developers like our team, but maybe not so easy to understand by the researchers. Let me know what do you think?

**Comment by Jen-Wenzel** [comment]
Sure, I can do that. Or would it also make a difference to remove auto-fixes (or have them optional) and just save all the output to the artifact? @romulogoncalves

**Comment by romulogoncalves** [comment]
I would say once we use pre-commit the auto-fixes should be there. The option to use the old make lint, it is for now for backward compatibility, but also it is easy to use by non-developers. Once the pre-commit is mature enough and we see we can make the default option, then it is just a question of update the menu options of cookiecutter.

**Comment by Jen-Wenzel** [comment]
Can be closed due to successful merge of changes -> https://github.com/FernLab/cookiecutter-py-package/commit/a65f6b39f95d1c5035762319273f85885bd2474c
